name: example
description: A sample command-line application.
version: 1.0.4
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  analyzer: ^7.3.0
  build: ^2.4.2
  source_gen: ^2.0.0
  auto_mapper:
    path: ../../auto_mapper

dev_dependencies:
  build_runner: ^2.4.15
